LajnaLegenden/project-foodie

- src/Pages/view-menu/components/Timeline.razor
Takes start and end date and converts all dates inbetween to a weekday.
> Cbg 63 Timeline component

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/ViewStart.razor
- src/Pages/view-menu/ViewStart.razor.css
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/Dishes.razor.css
- src/Pages/view-menu/components/MenuContainer.razor
- src/Pages/view-menu/components/MenuContainer.razor.css
- src/Pages/view-menu/components/Timeline.razor
- src/Pages/view-menu/components/Timeline.razor.css
- Removed all bootstrap and changed with css classes in all razor files in view-menu Folder
- Removed H2 tag in Timeline component
- Added css files scoped for all razor files in view-menu Folder
- Updated input tag in dishes component with a readonly
> Cbg 63 CSS

- src/Pages/view-menu/components/Timeline.razor
- src/Pages/view-menu/components/TimelineDay.razor
Added a Timeline day component and made it possible to pass parameters to Timeline component.
> Cbg 63 Parameters for Timeline and new component TimlineDay

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/Dishes.razor.css
- src/Pages/view-menu/components/MenuContainer.razor
Big Update
- Added the database to ViewMenu.razor.
- Added function to take the first week depending on which end date it is.
- Updated The category buttons to radioButtons.
- Fixed functionalites with the radioButtons.
- Updated CSS
- Passed down menu to MenuContainer and Dished.
> Cbg 63 category

- src/LocalDataDishes.json
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/MenuContainer.razor
- src/Program.cs
- src/_Imports.razor
- src/project-foodie.csproj
Added LocalStorage Save For Dishes
Saves As Json Format (Read And Write)
> Cbg 64 choose dishes

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/MenuContainer.razor
- src/Pages/view-menu/components/MenuContainer.razor.css
- src/Pages/view-menu/components/Overview.razor
> Cbg 63 view menu

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/MenuContainer.razor
Added New Functions To LocalStorage
> Local storage

- src/Pages/view-menu/components/Contents.razor
- src/Pages/view-menu/components/Contents.razor.css
- src/Pages/view-menu/components/Dishes.razor
_Doesn't use data from database._
- Allergen/Contents popup component.
- Open popup when clicking on dish-card image.
> Cbg 63 allergen view component

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/MenuContainer.razor
Changed dataformat in localsotragae
> Store all dishes in local storage

- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/Dishes.razor.css
- src/Pages/view-menu/components/MenuContainer.razor
- src/Pages/view-menu/components/MenuContainer.razor.css
- Food cards non-interactable when "no food" checkbox is checked.
- Resets quantity to 0 when "no food" checkbox is checked.
- Changes colors of quantity field and buttons to grayish when "no food" checkbox is checked.
> Cbg 64 no food checkbox

- src/Pages/view-menu/components/MenuContainer.razor
- Skip lunch label to adapt to meal type.
> Cbg 64 adapt label to meal type

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/components/Overview.razor
- src/Pages/view-menu/components/Overview.razor.css
- Choose Lunch are printed out
- Choose Dinners are printed out
- Total price for lunch + dinner
- Entire price for each day of which the person has chosen a dish
- Amount of dishes is printed out
- Which day the choise has been made
- If dish has not been chosen it will end being blank on dinner or lunch
> Get local storage from json

- src/Model/Category.cs
- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/components/MenuContainer.razor
- src/Pages/view-menu/components/MenuContainer.razor.css
- Moved category buttons to ViewMenu.razor to make them work on all days.
- Only show dishes for choosen category
> category buttons work on all days, and dishes sorted by category

- src/Pages/view-menu/ViewMenu.razor
- bugfix on radio buttons (Accidently removed them in conflict merge)
- bugfix on overview page (Accidently removed the menu in conflict merge)
> Bugfixes for category and overview

- src/Pages/_Host.cshtml
- src/Pages/view-menu/components/TimeLineSection.razor
- src/Pages/view-menu/components/TimeLineSection.razor.css
- src/Pages/view-menu/components/Timeline.razor
- src/Pages/view-menu/components/Timeline.razor.css
- src/appsettings.Development.json
Timeline has mobile, tablet and desktop state
> Mobile reponsive timeline

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/ViewStart.razor
- Changed "föregående dag" to "föregående".
- Changed date format to yyyy-mm-dd in View start
> Cbg 63 view menu changed "föregående dag" and date format

- src/Pages/view-menu/ViewMenu.razor
- Added If statment that checks if its not a pc  / desktop then use the auto scroll.
> Bugfix Scroll on pc

- src/Pages/view-menu/components/Overview.razor
- Fixed bug with empty localstorage ( Crashed the program before )
> Bugfix with empty localstorage

- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/MenuContainer.razor
- Quantity of dishes reset to 0 when "disable food" checkbox is checked.
> CBG-346 Fixed reset dishes quantity to 0 when checkbox checked

- src/Shared/NavHeader.razor
- src/Shared/NavHeader.razor.css
- Added Cart Into Navbar
- Shows A Little Icon Of Current Items In The Cart Based On What Has Been Chosen 
- It Fetches Data From LocalStorage On Start
> Cbg 324 show orderd food in a cart

- src/Model/DatabaseContext.cs
- src/Modules/localstorage.cs
- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/components/Confirmed.razor
- src/Pages/view-menu/components/Overview.razor
- Moved Localstorage from Overview to a module.
- Created a confirmed view component.
- Added confimed view component in ViewMenu.
- Raised the max index in ViewMenu.
- Cleaned up some unused code.
> Cbg 65 order confirmed view

- src/Migrations/20230221135020_AddDateAndOrderTypeToOrederItem.Designer.cs
- src/Migrations/20230221135020_AddDateAndOrderTypeToOrederItem.cs
- src/Model/OrderItem.cs
- src/Pages/webmaster/components/Db.razor
- src/Program.cs
- src/Repository/Interfaces/IOrderRepository.cs
- src/Repository/Interfaces/IRepositoryBase.cs
- src/Repository/Interfaces/IRepositoryWrapper.cs
- src/Repository/OrderRepository.cs
- src/Repository/RepositoryBase.cs
- src/Repository/RepositoryWrapper.cs
- Restructure repository to use Interfaces, RepositoryBase and RepositoryWrapper (only applied to OrderRepository atm)
- Add order mock data when fill db.
- Update OrderItem to contain date and  OrderType, so we know which dish is meant for which day in case the same dish can be ordered on multiple days.
> Cbg 354 order repository

- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/components/MenuContainer.razor.css
- src/Pages/view-menu/components/TimeLineSection.razor
- src/Pages/view-menu/components/TimeLineSection.razor.css
- src/Pages/view-menu/components/Timeline.razor
- src/Shared/NavHeader.razor.css
- Decreased margin in day container in ViewMenu
- Decreased margin in skip-container in MenuContainer
- Bugfix with menu
- Changed color on a links when active in time line
- Decreased Header hight in Header
> Cbg 355 Menu fit in full page

- .gitignore
- Dockerfile
- src/package-lock.json
- src/package.json
- src/postcss.config.js
- src/project-foodie.csproj
> CBG-327 css auto prefixer

- src/Pages/view-menu/components/Contents.razor
- src/Pages/view-menu/components/Contents.razor.css
- Nutritional values table added to info popup
> add nutriotional value to popup

- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/Dishes.razor.css
> add info button to dish card

- src/Pages/_Host.cshtml
- src/Pages/view-menu/components/Confirmed.razor
- src/Pages/view-menu/components/Confirmed.razor.css
- Added confetti rain when gets to the confirmed page
> Cbg 60 design order confirmed view

- src/Pages/view-menu/components/Dishes.razor
- src/Pages/view-menu/components/Dishes.razor.css
- Fixed back old choose btn.
- Added new css to the choose btn and add container.
> Fixed back choose btn

- src/Modules/DayMenuHelper.cs
- src/Pages/my-page/MyPage.razor
- src/Pages/my-page/components/OrderTable.razor
- src/Pages/my-page/components/OrderTable.razor.css
- src/Pages/webmaster/components/Db.razor
- Order details in orderTable
- Added method to DayMenuHelper
- Created CSS-file for orderTable
- Fixed issue with ghost dish
- Created a me page with link to order history
> Cbg 73 Order details

- src/Pages/view-menu/ViewMenu.razor
- src/Pages/view-menu/components/Confirmed.razor
- Count meals, not dishes
- empty cart when order is placed
> Fix meal count

- src/Pages/view-menu/components/Dishes.razor.css
- Fixed issue with plus and minus buttons, it now shows correct design on all browsers.
- Fixed issue with the li tag design on all browsers
> Fixed Issue With Different Browser Design

- src/Pages/view-menu/components/Confirmed.razor
- src/Pages/view-menu/components/Dishes.razor.css
- src/Services/CartService.cs
- Fixed issue with Wrong Varukorg Count
- Fixed Issue With Safari, It now Shows Correct Design
- Fixed Issue With Confirmed Window To Show Correct Count Of Dishes Ordered
> Bug fixes safari varukorg overview

- src/Services/CartService.cs
- Added If Statement To Check If Value Is Bellow 0, is so return 0. This fixes the issue with -1 On Cart
> Fixed Issue With -1 On Cart

- src/Pages/view-menu/ViewMenu.razor.css
- src/Pages/view-menu/ViewStart.razor
- src/Pages/view-menu/components/MenuContainer.razor.css
- src/Shared/MobileHeader.razor
- src/Shared/MobileHeader.razor.css
- src/Shared/NavHeader.razor
- src/Shared/NavHeader.razor.css
- src/wwwroot/css/site.css
- Bugfxies on Mobile Header
- Bugfxies on NavHeader
- Bugfxies on card container
- Bugfxies on Start Menu
> Sprint 4 bugfixes
